### PR TITLE
Testing part 1 - Pair programming

### PR DESCRIPTION
**Pull request by rominana**
### Testing To Do list: part 1 :smile: 
In this project, @diegoyon  and I : 
- Created test files for a file containing the add item and delete item functions.
- Mocked a storage object to "imitate" localStorage operations.
- Mocked HTML to test if add/delete functions add or remove exactly one li element to/from the list in the DOM.
- Created tests using the describe() method.

_side note: we also had to apply a test on a createLi function to check the correct functioning of add and remove_

### CODE REVIEW

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @rominana  @diegoyon , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 

## Required Changes ♻️

- [ ] It seems like all your test failed, please fix them because functions responsible for adding and deleting list items are tested and the tests need to pass. see the screenshots below :point_down: 

Screenshot from 2022-07-13 20-21-59


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rominana** [comment]
hello @codecaiine! Thank you very much for the feedback. Could you please help us to figure it out what is the issue? Because this is what we see from our side
image

**Comment by rominana** [comment]
All the suggested changes have been applied :+1: 
image

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @rominana and @diegoyon 👋Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.
- Github inline comments feature is used properly.
- You asked for the changes in a friendly and polite way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
